# Generated by Django 6.0.7 on 2026-08-25 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('siape', models.CharField(max_length=20, unique=True)),
                ('bloco_responsavel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('bloco', models.CharField(max_length=10)),
                ('streak_dias', models.IntegerField(default=0)),
                ('pontuacao_geral', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('estudante_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.estudante')),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClearOrder.quarto'),
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.quarto')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoReparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Em Aberto', max_length=50)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_prazo', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.cronograma')),
                ('estudante_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vistoria', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aprovado', models.BooleanField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.monitor')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearOrder.quarto')),
            ],
        ),
    ]
