# Generated by Django 6.0.7 on 2026-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='siape',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
