# Generated by Django 6.0.7 on 2026-09-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearOrder', '0002_estudante_cpf_monitor_cpf_alter_monitor_siape'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TarefaLimpeza',
            new_name='Tarefa',
        ),
    ]
