# Generated by Django 6.0.7 on 2026-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearOrder', '0003_rename_tarefalimpeza_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreparo',
            name='categoria',
            field=models.CharField(default='outros', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitacaoreparo',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=150),
        ),
    ]
