# Generated by Django 6.0.7 on 2026-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearOrder', '0004_solicitacaoreparo_categoria_solicitacaoreparo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
